import type { Metadata } from "next"
import ThemeRegistry from "./ThemeRegistry"
import { ClerkProvider } from "@clerk/nextjs"


export const metadata: Metadata = {
  title: "HaySam",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeRegistry>{children}</ThemeRegistry>
        </body>
      </html>
    </ClerkProvider>
  )
}
